### ISSUE TITLE
Add Favicon.ico to the project

### ISSUE THREAD

**Issue by lusarz** [driggl/linklog#38]
## Overview

For now let's add just a sample favicon without any fancy stuff.

- Create a W-letter favicon and replace the default Vue one.

**Comment by lusarz** [comment]
@swilgosz Do you have appropriate ico file ?

**Comment by swilgosz** [comment]
@lusarz not at the moment. I will prepare one next week

**Comment by swilgosz** [comment]
Resolved in: https://github.com/driggl/linklog/commit/dd677a3521d97597c1e570c67aa28dfc4fee06db
