### ISSUE TITLE
Listing recent articles.

### ISSUE THREAD

**Issue by swilgosz** [driggl/linklog#4]
List recent articles using infinite scroll.

Single entry should contain:

- [x] Title
- [x] Excerpt (or the first paragraph of the article content)
- [x] Author info: Name (login)
  - [x] if profile URL is present, link to the URL
  - [x] if avatar URL present, show the avatar - otherwise a placeholder
- [x] sort articles by publication date
- [x] infinity scroll.

### Optional, but nice-to-have

This section can be extracted to a separate issue and tackled at the end of the project if there is a time for.

- Group articles by the day of publication.

### Resources

- [Figma mockups](https://www.figma.com/file/TLWl94YRhXLaBuLhub1Uo2XC/frontend-flow?node-id=400%3A39)
- [API endpoint](https://documenter.getpostman.com/view/4406272/SVSGMq6b?version=latest#609cac98-a99f-4e7d-9804-7a36d21f96a7)

### UI - TODO
- [x] Display excerpt from backend
- [x] Verify if everything works properly regarding SEO
- [x] Beautify

**Comment by swilgosz** [comment]
@lusarz 

If possible, please adjust the color set - it's not a super big requirement if it's not trivial to change color sets in vuetify to those not included in the standard sets.

![image](https://user-images.githubusercontent.com/8088317/84565836-67563e80-ad6c-11ea-9226-a2a0ee456930.png)

![image](https://user-images.githubusercontent.com/8088317/84565843-79d07800-ad6c-11ea-848a-e8a56994da16.png)


There are some data missing:

1. Author username hooked up to the profile URL if present. Should be a circle. I suggest to play around with lists and cards components with avatars: 
  - https://vuetifyjs.com/en/components/lists/#avatar-with-3-lines
  - https://vuetifyjs.com/en/components/cards/

2. Read-More Link


For more referrals, feel free to check: https://www.figma.com/file/TLWl94YRhXLaBuLhub1Uo2XC/webdevflow.com?node-id=400%3A39

**Comment by lusarz** [comment]
@swilgosz Please check https://webdevflow.com/ 
1) I used list for every item
2) I'm not sure if we need Read-More Link - whole article item on list is clickable. If you want it anyway, please let me know
3) I also used color scheme you added above

**Comment by swilgosz** [comment]
@lusarz it is great! The only minor thing I would change is to move the author info under the title. What do you think?

**Comment by lusarz** [comment]
@swilgosz I moved author under the title and added "Read more" link. Any further suggestions about styling welcomed.
