### ISSUE TITLE
User registrations - Standard Flow

### ISSUE THREAD

**Issue by swilgosz** [driggl/linklog#5]
### Overview

Register new users using standard flow.

- [x] Registration/Login functionality should be accessible via the popup
- [x] Should be accessible from the top nav

Attributes to register new user:
- [x] Email
- [x] login (optional)
- [x] password
- [x] accept Privacy Policy

- [ ] When login/email is already taken, show this information saying which field is invalid.
![image](https://user-images.githubusercontent.com/8088317/84566464-a1760f00-ad71-11ea-83c6-64b0214f26d3.png)

- [x] When you successfully register, show notification about it.
- [x] when you submit the form correctly, auto-login the user
- [x] Buttons should use PRIMARY color (greenish)
- [ ] Unit tests

### Resources

- [API Endpoint](https://documenter.getpostman.com/view/4406272/SVSGMq6b?version=latest#135582e7-0d02-4667-9aaf-5ac73cb973b3)
- [Mockups](https://www.figma.com/file/TLWl94YRhXLaBuLhub1Uo2XC/frontend-flow?node-id=142%3A2)

### Suggested vuetify components:

- https://vuetifyjs.com/en/components/tooltips/#visibility
- https://vuetifyjs.com/en/components/snackbars/
- [Built-in Vuetify forms validation](https://vuetifyjs.com/en/components/forms/)

**Comment by swilgosz** [comment]
I've added a feedback as another issue: https://github.com/driggl/linklog/issues/43

**Comment by swilgosz** [comment]
Registration works properly but there are some UX issues to be fixed. 

- when you submit the form correctly, auto-login the user
- When login/email is already taken, show this information saying which field is invalid.
- When you successfully register, show notification about it.

![image](https://user-images.githubusercontent.com/8088317/84566464-a1760f00-ad71-11ea-83c6-64b0214f26d3.png)


Possible vuetify components:

- https://vuetifyjs.com/en/components/tooltips/#visibility
- https://vuetifyjs.com/en/components/snackbars/

**Comment by lusarz** [comment]
@swilgosz Do you have proposition regarding success message exact text ?

**Comment by lusarz** [comment]
@swilgosz

> When login/email is already taken, show this information saying which field is invalid.

Backend needs to return this information

**Comment by swilgosz** [comment]
> Do you have proposition regarding success message exact text ?

@lusarz Wha about "Thanks for joining!" ? ;)
